### ISSUE TITLE
Why ?

### ISSUE THREAD

**Issue by 0x454d505459** [xKenyh/Discord-Token-Finder#9]
Why creating a bloated script for that when you can just
1) Open any website that can encode in base64 or
2) run: `echo "ID" | base64` in a linux terminal

This script needs 3 pypi modules + a python install for not much.

Im just sayin'

It's also useless btw.

**Comment by xKenyh** [comment]
i did this for fun, if you don't like it, just ignore it :)

**Comment by MrinmoyHaloi** [comment]
> Why creating a bloated script for that when you can just
> 
> 1. Open any website that can encode in base64 or
> 2. run: `echo "ID" | base64` in a linux terminal
> 
> This script needs 3 pypi modules + a python install for not much.
> 
> Im just sayin'
> 
> It's also useless btw.

I agree

**Comment by 0x454d505459** [comment]
> i did this for fun, if you don't like it, just ignore it :)

Dawn, fun is weird some times, especially these days. Hope you enjoy your project I guess.
